# Generated by Django 4.2.3 on 2023-08-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=20)),
            ],
        ),
    ]
